stages:
  - dependencies
  - build
  - deploy

dependencies:
  stage: dependencies
  image: golang:1.12
  cache:
    paths:
      - .cache
  script:
    - export GOPATH="$CI_PROJECT_DIR/.cache"
    - export GOBIN="$GOPATH/bin"
    - mkdir -p .cache
    - go get -v .
  tags:
    - docker

build:
  stage: build
  image: golang:1.12
  cache:
    paths:
      - .cache
  script:
    - export GOPATH="$CI_PROJECT_DIR/.cache"
    - export GOBIN="$GOPATH/bin"
    - go build
  artifacts:
    paths:
     - nocontent
  tags:
    - docker

deploy:
  stage: deploy
  image: python:3-buster
  script:
    - apt update && apt install -y zip
    - pip install awscli
    - zip package.zip nocontent Inconsolata.ttf
    - aws lambda update-function-code --function-name=nocontent --zip=fileb://package.zip
  tags:
    - docker
